27714691,5139199
27798108,5214547
27741871,5280057
27697561,GPUassert: an illegal memory access was encountered ./src/GPU/dynamic-edge-update.cu 810
Traceback (most recent call last):
  File "run.py", line 102, in <module>
    run(exec_map[(algo,gpuflag)]+ " ./datasets/{}.in ./queries/edge-update-queries/queries_{}/{}_queries ./output/{} {}".format(dataset, batch, dataset, outfile, numthread), shell=True, check=True)
  File "/usr/lib64/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command './exec/GPU/deu ./datasets/email-enron.in ./queries/edge-update-queries/queries_5000/email-enron_queries ./output/p64_q5000_gpu_dynedge_email-enron.txt ['32']' returned non-zero exit status 188.
27775164,GPUassert: an illegal memory access was encountered ./src/GPU/dynamic-edge-update.cu 810
Traceback (most recent call last):
  File "run.py", line 102, in <module>
    run(exec_map[(algo,gpuflag)]+ " ./datasets/{}.in ./queries/edge-update-queries/queries_{}/{}_queries ./output/{} {}".format(dataset, batch, dataset, outfile, numthread), shell=True, check=True)
  File "/usr/lib64/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command './exec/GPU/deu ./datasets/email-enron.in ./queries/edge-update-queries/queries_100000/email-enron_queries ./output/p64_q100000_gpu_dynedge_email-enron.txt ['32']' returned non-zero exit status 188.
