29142438,2031954
29190990,2035633
29232684,2081981
29263298,2256301
29216644,GPUassert: an illegal memory access was encountered ./src/GPU/dynamic-edge-update.cu 810
Traceback (most recent call last):
  File "run.py", line 102, in <module>
    run(exec_map[(algo,gpuflag)]+ " ./datasets/{}.in ./queries/edge-update-queries/queries_{}/{}_queries ./output/{} {}".format(dataset, batch, dataset, outfile, numthread), shell=True, check=True)
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command './exec/GPU/deu ./datasets/email-enron.in ./queries/edge-update-queries/queries_100000/email-enron_queries ./output/p64_q100000_gpu_dynedge_email-enron.txt ['32']' returned non-zero exit status 188.
