
./datasets/PGPgiantcompo.in,4669647,10,8103,43,44,10,51817,3,42,41958,102055
./datasets/PGPgiantcompo.in,4744898,100,8266,44,44,9,53034,20,41,44163,105660
./datasets/PGPgiantcompo.in,4698997,1000,14274,48,54,11,52486,135,40,56082,123167
./datasets/PGPgiantcompo.in,4675986,5000,39918,49,44,11,53458,389,39,62713,156664
nvcc error   : 'gcc' died due to signal 2 
Traceback (most recent call last):
  File "run.py", line 104, in <module>
    run(command_map[(algo,gpuflag)], shell=True, check=True)
  File "/usr/lib/python3.8/subprocess.py", line 495, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib/python3.8/subprocess.py", line 1020, in communicate
    self.wait()
  File "/usr/lib/python3.8/subprocess.py", line 1083, in wait
    return self._wait(timeout=timeout)
  File "/usr/lib/python3.8/subprocess.py", line 1806, in _wait
    (pid, sts) = self._try_wait(0)
  File "/usr/lib/python3.8/subprocess.py", line 1764, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt
./datasets/PGPgiantcompo.in,GPUassert: no CUDA-capable device is detected ./src/GPU/dynamic-edge-update.cu 742
Traceback (most recent call last):
  File "/DATA/prajjwal/dynamic-percolation-centrality/run.py", line 114, in <module>
    run(exec_map[(algo,gpuflag)]+ " ./datasets/{}.in ./queries/edge-update-queries/queries_{}/{}_queries ./output/{} {}".format(dataset, batch, dataset, outfile, numthread), shell=True, check=True)
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'CUDA_VISIBLE_DEVICES=2 ./exec/GPU/deu ./datasets/PGPgiantcompo.in ./queries/edge-update-queries/queries_10/PGPgiantcompo_queries ./output/p64_q10_gpu_dynedge_PGPgiantcompo.txt ['32']' returned non-zero exit status 100.
./datasets/PGPgiantcompo.in,GPUassert: no CUDA-capable device is detected ./src/GPU/dynamic-edge-update.cu 742
Traceback (most recent call last):
  File "/DATA/prajjwal/dynamic-percolation-centrality/run.py", line 114, in <module>
    run(exec_map[(algo,gpuflag)]+ " ./datasets/{}.in ./queries/edge-update-queries/queries_{}/{}_queries ./output/{} {}".format(dataset, batch, dataset, outfile, numthread), shell=True, check=True)
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'CUDA_VISIBLE_DEVICES=2 ./exec/GPU/deu ./datasets/PGPgiantcompo.in ./queries/edge-update-queries/queries_100/PGPgiantcompo_queries ./output/p64_q100_gpu_dynedge_PGPgiantcompo.txt ['32']' returned non-zero exit status 100.
./datasets/PGPgiantcompo.in,GPUassert: no CUDA-capable device is detected ./src/GPU/dynamic-edge-update.cu 742
Traceback (most recent call last):
  File "/DATA/prajjwal/dynamic-percolation-centrality/run.py", line 114, in <module>
    run(exec_map[(algo,gpuflag)]+ " ./datasets/{}.in ./queries/edge-update-queries/queries_{}/{}_queries ./output/{} {}".format(dataset, batch, dataset, outfile, numthread), shell=True, check=True)
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'CUDA_VISIBLE_DEVICES=2 ./exec/GPU/deu ./datasets/PGPgiantcompo.in ./queries/edge-update-queries/queries_1000/PGPgiantcompo_queries ./output/p64_q1000_gpu_dynedge_PGPgiantcompo.txt ['32']' returned non-zero exit status 100.
./datasets/PGPgiantcompo.in,GPUassert: no CUDA-capable device is detected ./src/GPU/dynamic-edge-update.cu 742
Traceback (most recent call last):
  File "/DATA/prajjwal/dynamic-percolation-centrality/run.py", line 114, in <module>
    run(exec_map[(algo,gpuflag)]+ " ./datasets/{}.in ./queries/edge-update-queries/queries_{}/{}_queries ./output/{} {}".format(dataset, batch, dataset, outfile, numthread), shell=True, check=True)
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'CUDA_VISIBLE_DEVICES=2 ./exec/GPU/deu ./datasets/PGPgiantcompo.in ./queries/edge-update-queries/queries_5000/PGPgiantcompo_queries ./output/p64_q5000_gpu_dynedge_PGPgiantcompo.txt ['32']' returned non-zero exit status 100.
