./datasets/slashdot.in,GPUassert: out of memory ./src/GPU/dynamic-edge-update.cu 742
Traceback (most recent call last):
  File "run.py", line 113, in <module>
    run(exec_map[(algo,gpuflag)]+ " ./datasets/{}.in ./queries/edge-update-queries/queries_{}/{}_queries ./output/{} {}".format(dataset, batch, dataset, outfile, numthread), shell=True, check=True)
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'CUDA_VISIBLE_DEVICES=2 ./exec/GPU/deu ./datasets/slashdot.in ./queries/edge-update-queries/queries_10/slashdot_queries ./output/p64_q10_gpu_dynedge_slashdot.txt ['32']' returned non-zero exit status 2.
./datasets/slashdot.in,GPUassert: out of memory ./src/GPU/dynamic-edge-update.cu 742
Traceback (most recent call last):
  File "run.py", line 113, in <module>
    run(exec_map[(algo,gpuflag)]+ " ./datasets/{}.in ./queries/edge-update-queries/queries_{}/{}_queries ./output/{} {}".format(dataset, batch, dataset, outfile, numthread), shell=True, check=True)
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'CUDA_VISIBLE_DEVICES=2 ./exec/GPU/deu ./datasets/slashdot.in ./queries/edge-update-queries/queries_100/slashdot_queries ./output/p64_q100_gpu_dynedge_slashdot.txt ['32']' returned non-zero exit status 2.
./datasets/slashdot.in,GPUassert: out of memory ./src/GPU/dynamic-edge-update.cu 742
Traceback (most recent call last):
  File "run.py", line 113, in <module>
    run(exec_map[(algo,gpuflag)]+ " ./datasets/{}.in ./queries/edge-update-queries/queries_{}/{}_queries ./output/{} {}".format(dataset, batch, dataset, outfile, numthread), shell=True, check=True)
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'CUDA_VISIBLE_DEVICES=2 ./exec/GPU/deu ./datasets/slashdot.in ./queries/edge-update-queries/queries_1000/slashdot_queries ./output/p64_q1000_gpu_dynedge_slashdot.txt ['32']' returned non-zero exit status 2.
./datasets/slashdot.in,GPUassert: out of memory ./src/GPU/dynamic-edge-update.cu 742
Traceback (most recent call last):
  File "run.py", line 113, in <module>
    run(exec_map[(algo,gpuflag)]+ " ./datasets/{}.in ./queries/edge-update-queries/queries_{}/{}_queries ./output/{} {}".format(dataset, batch, dataset, outfile, numthread), shell=True, check=True)
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'CUDA_VISIBLE_DEVICES=2 ./exec/GPU/deu ./datasets/slashdot.in ./queries/edge-update-queries/queries_5000/slashdot_queries ./output/p64_q5000_gpu_dynedge_slashdot.txt ['32']' returned non-zero exit status 2.
