2573964,40956
2591016,41026
2570583,46591
2602104,56771
2587248,GPUassert: an illegal memory access was encountered ./src/GPU/dynamic-edge-update.cu 810
Traceback (most recent call last):
  File "run.py", line 102, in <module>
    run(exec_map[(algo,gpuflag)]+ " ./datasets/{}.in ./queries/edge-update-queries/queries_{}/{}_queries ./output/{} {}".format(dataset, batch, dataset, outfile, numthread), shell=True, check=True)
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command './exec/GPU/deu ./datasets/web-indochina-2004.in ./queries/edge-update-queries/queries_100000/web-indochina-2004_queries ./output/p64_q100000_gpu_dynedge_web-indochina-2004.txt ['32']' returned non-zero exit status 188.
