./datasets/web-indochina-2004.in,390800,10,148720
./datasets/web-indochina-2004.in,364309,100,147491
./datasets/web-indochina-2004.in,400513,1000,179381
./datasets/web-indochina-2004.in,362569,5000,174254
./datasets/web-indochina-2004.in,GPUassert: no CUDA-capable device is detected ./src/GPU/static-edge-update.cu 259
Traceback (most recent call last):
  File "/DATA/prajjwal/dynamic-percolation-centrality/run.py", line 114, in <module>
    run(exec_map[(algo,gpuflag)]+ " ./datasets/{}.in ./queries/edge-update-queries/queries_{}/{}_queries ./output/{} {}".format(dataset, batch, dataset, outfile, numthread), shell=True, check=True)
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'CUDA_VISIBLE_DEVICES=2 ./exec/GPU/seu ./datasets/web-indochina-2004.in ./queries/edge-update-queries/queries_10/web-indochina-2004_queries ./output/p64_q10_gpu_statedge_web-indochina-2004.txt ['32']' returned non-zero exit status 100.
./datasets/web-indochina-2004.in,GPUassert: no CUDA-capable device is detected ./src/GPU/static-edge-update.cu 259
Traceback (most recent call last):
  File "/DATA/prajjwal/dynamic-percolation-centrality/run.py", line 114, in <module>
    run(exec_map[(algo,gpuflag)]+ " ./datasets/{}.in ./queries/edge-update-queries/queries_{}/{}_queries ./output/{} {}".format(dataset, batch, dataset, outfile, numthread), shell=True, check=True)
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'CUDA_VISIBLE_DEVICES=2 ./exec/GPU/seu ./datasets/web-indochina-2004.in ./queries/edge-update-queries/queries_100/web-indochina-2004_queries ./output/p64_q100_gpu_statedge_web-indochina-2004.txt ['32']' returned non-zero exit status 100.
./datasets/web-indochina-2004.in,GPUassert: no CUDA-capable device is detected ./src/GPU/static-edge-update.cu 259
Traceback (most recent call last):
  File "/DATA/prajjwal/dynamic-percolation-centrality/run.py", line 114, in <module>
    run(exec_map[(algo,gpuflag)]+ " ./datasets/{}.in ./queries/edge-update-queries/queries_{}/{}_queries ./output/{} {}".format(dataset, batch, dataset, outfile, numthread), shell=True, check=True)
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'CUDA_VISIBLE_DEVICES=2 ./exec/GPU/seu ./datasets/web-indochina-2004.in ./queries/edge-update-queries/queries_1000/web-indochina-2004_queries ./output/p64_q1000_gpu_statedge_web-indochina-2004.txt ['32']' returned non-zero exit status 100.
./datasets/web-indochina-2004.in,GPUassert: no CUDA-capable device is detected ./src/GPU/static-edge-update.cu 259
Traceback (most recent call last):
  File "/DATA/prajjwal/dynamic-percolation-centrality/run.py", line 114, in <module>
    run(exec_map[(algo,gpuflag)]+ " ./datasets/{}.in ./queries/edge-update-queries/queries_{}/{}_queries ./output/{} {}".format(dataset, batch, dataset, outfile, numthread), shell=True, check=True)
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'CUDA_VISIBLE_DEVICES=2 ./exec/GPU/seu ./datasets/web-indochina-2004.in ./queries/edge-update-queries/queries_5000/web-indochina-2004_queries ./output/p64_q5000_gpu_statedge_web-indochina-2004.txt ['32']' returned non-zero exit status 100.
