./datasets/web-indochina-2004.in,2367003,10,3518,40,19,9,18499,3,48,18667,40837
./datasets/web-indochina-2004.in,2395280,100,3660,40,18,9,18434,15,49,18615,40876
./datasets/web-indochina-2004.in,2370632,1000,4691,41,22,9,19523,98,48,20819,45286
./datasets/web-indochina-2004.in,2361559,5000,10561,40,27,10,19404,270,47,26562,56963
./datasets/web-indochina-2004.in,GPUassert: no CUDA-capable device is detected ./src/GPU/dynamic-edge-update.cu 742
Traceback (most recent call last):
  File "/DATA/prajjwal/dynamic-percolation-centrality/run.py", line 114, in <module>
    run(exec_map[(algo,gpuflag)]+ " ./datasets/{}.in ./queries/edge-update-queries/queries_{}/{}_queries ./output/{} {}".format(dataset, batch, dataset, outfile, numthread), shell=True, check=True)
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'CUDA_VISIBLE_DEVICES=2 ./exec/GPU/deu ./datasets/web-indochina-2004.in ./queries/edge-update-queries/queries_10/web-indochina-2004_queries ./output/p64_q10_gpu_dynedge_web-indochina-2004.txt ['32']' returned non-zero exit status 100.
./datasets/web-indochina-2004.in,GPUassert: no CUDA-capable device is detected ./src/GPU/dynamic-edge-update.cu 742
Traceback (most recent call last):
  File "/DATA/prajjwal/dynamic-percolation-centrality/run.py", line 114, in <module>
    run(exec_map[(algo,gpuflag)]+ " ./datasets/{}.in ./queries/edge-update-queries/queries_{}/{}_queries ./output/{} {}".format(dataset, batch, dataset, outfile, numthread), shell=True, check=True)
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'CUDA_VISIBLE_DEVICES=2 ./exec/GPU/deu ./datasets/web-indochina-2004.in ./queries/edge-update-queries/queries_100/web-indochina-2004_queries ./output/p64_q100_gpu_dynedge_web-indochina-2004.txt ['32']' returned non-zero exit status 100.
./datasets/web-indochina-2004.in,GPUassert: no CUDA-capable device is detected ./src/GPU/dynamic-edge-update.cu 742
Traceback (most recent call last):
  File "/DATA/prajjwal/dynamic-percolation-centrality/run.py", line 114, in <module>
    run(exec_map[(algo,gpuflag)]+ " ./datasets/{}.in ./queries/edge-update-queries/queries_{}/{}_queries ./output/{} {}".format(dataset, batch, dataset, outfile, numthread), shell=True, check=True)
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'CUDA_VISIBLE_DEVICES=2 ./exec/GPU/deu ./datasets/web-indochina-2004.in ./queries/edge-update-queries/queries_1000/web-indochina-2004_queries ./output/p64_q1000_gpu_dynedge_web-indochina-2004.txt ['32']' returned non-zero exit status 100.
./datasets/web-indochina-2004.in,GPUassert: no CUDA-capable device is detected ./src/GPU/dynamic-edge-update.cu 742
Traceback (most recent call last):
  File "/DATA/prajjwal/dynamic-percolation-centrality/run.py", line 114, in <module>
    run(exec_map[(algo,gpuflag)]+ " ./datasets/{}.in ./queries/edge-update-queries/queries_{}/{}_queries ./output/{} {}".format(dataset, batch, dataset, outfile, numthread), shell=True, check=True)
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'CUDA_VISIBLE_DEVICES=2 ./exec/GPU/deu ./datasets/web-indochina-2004.in ./queries/edge-update-queries/queries_5000/web-indochina-2004_queries ./output/p64_q5000_gpu_dynedge_web-indochina-2004.txt ['32']' returned non-zero exit status 100.
