./datasets/web-webbase-2001.in,508374,10,248163
./datasets/web-webbase-2001.in,488360,100,254209
./datasets/web-webbase-2001.in,488012,1000,263377
./datasets/web-webbase-2001.in,489471,5000,292787
./datasets/web-webbase-2001.in,GPUassert: no CUDA-capable device is detected ./src/GPU/static-edge-update.cu 259
Traceback (most recent call last):
  File "/DATA/prajjwal/dynamic-percolation-centrality/run.py", line 114, in <module>
    run(exec_map[(algo,gpuflag)]+ " ./datasets/{}.in ./queries/edge-update-queries/queries_{}/{}_queries ./output/{} {}".format(dataset, batch, dataset, outfile, numthread), shell=True, check=True)
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'CUDA_VISIBLE_DEVICES=2 ./exec/GPU/seu ./datasets/web-webbase-2001.in ./queries/edge-update-queries/queries_10/web-webbase-2001_queries ./output/p64_q10_gpu_statedge_web-webbase-2001.txt ['32']' returned non-zero exit status 100.
./datasets/web-webbase-2001.in,GPUassert: no CUDA-capable device is detected ./src/GPU/static-edge-update.cu 259
Traceback (most recent call last):
  File "/DATA/prajjwal/dynamic-percolation-centrality/run.py", line 114, in <module>
    run(exec_map[(algo,gpuflag)]+ " ./datasets/{}.in ./queries/edge-update-queries/queries_{}/{}_queries ./output/{} {}".format(dataset, batch, dataset, outfile, numthread), shell=True, check=True)
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'CUDA_VISIBLE_DEVICES=2 ./exec/GPU/seu ./datasets/web-webbase-2001.in ./queries/edge-update-queries/queries_100/web-webbase-2001_queries ./output/p64_q100_gpu_statedge_web-webbase-2001.txt ['32']' returned non-zero exit status 100.
./datasets/web-webbase-2001.in,GPUassert: no CUDA-capable device is detected ./src/GPU/static-edge-update.cu 259
Traceback (most recent call last):
  File "/DATA/prajjwal/dynamic-percolation-centrality/run.py", line 114, in <module>
    run(exec_map[(algo,gpuflag)]+ " ./datasets/{}.in ./queries/edge-update-queries/queries_{}/{}_queries ./output/{} {}".format(dataset, batch, dataset, outfile, numthread), shell=True, check=True)
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'CUDA_VISIBLE_DEVICES=2 ./exec/GPU/seu ./datasets/web-webbase-2001.in ./queries/edge-update-queries/queries_1000/web-webbase-2001_queries ./output/p64_q1000_gpu_statedge_web-webbase-2001.txt ['32']' returned non-zero exit status 100.
./datasets/web-webbase-2001.in,GPUassert: no CUDA-capable device is detected ./src/GPU/static-edge-update.cu 259
Traceback (most recent call last):
  File "/DATA/prajjwal/dynamic-percolation-centrality/run.py", line 114, in <module>
    run(exec_map[(algo,gpuflag)]+ " ./datasets/{}.in ./queries/edge-update-queries/queries_{}/{}_queries ./output/{} {}".format(dataset, batch, dataset, outfile, numthread), shell=True, check=True)
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'CUDA_VISIBLE_DEVICES=2 ./exec/GPU/seu ./datasets/web-webbase-2001.in ./queries/edge-update-queries/queries_5000/web-webbase-2001_queries ./output/p64_q5000_gpu_statedge_web-webbase-2001.txt ['32']' returned non-zero exit status 100.
